
package com.atlassian.theplugin.crucible.api.soap.xfire;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Thu Feb 07 14:49:09 CET 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

public final class RpcAuthServiceName_AuthPort_Client {

    private static final QName SERVICE_NAME = new QName("http://rpc.spi.crucible.atlassian.com/", "Auth");

    private RpcAuthServiceName_AuthPort_Client() {
    }

    public static void main(String args[]) throws Exception {

		args = new String[] {"http://lech.atlassian.pl:8060/service/auth?wsdl"};

		if (args.length == 0) {
            System.out.println("please specify wsdl");
            System.exit(1); 
        }
        URL wsdlURL = null;
        File wsdlFile = new File(args[0]);
        try {
            if (wsdlFile.exists()) {
                wsdlURL = wsdlFile.toURL();
            } else {
                wsdlURL = new URL(args[0]);
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
      
        Auth ss = new Auth(wsdlURL, SERVICE_NAME);
        RpcAuthServiceName port = ss.getAuthPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_arg0 = "";
        java.lang.String _login_arg1 = "";
        java.lang.String _login__return = port.login(_login_arg0, _login_arg1);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking logout...");
        java.lang.String _logout_arg0 = "";
        port.logout(_logout_arg0);


        }

        System.exit(0);
    }

}
