
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.atlassian.theplugin.crucible.api.soap.xfire;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Thu Feb 07 14:49:09 CET 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@javax.jws.WebService(name = "RpcAuthServiceName", serviceName = "Auth",
                      portName = "AuthPort",
                      targetNamespace = "http://rpc.spi.crucible.atlassian.com/", 
                      wsdlLocation = "file:/C:/Dev/ThePlugin/src/main/java/com/atlassian/theplugin/crucible/api/soap/auth.wsdl" ,
		      endpointInterface = "com.atlassian.theplugin.crucible.api.soap.xfire.RpcAuthServiceName")
                      
public class RpcAuthServiceNameImpl implements RpcAuthServiceName {

    private static final Logger LOG = Logger.getLogger(RpcAuthServiceNameImpl.class.getName());

    /* (non-Javadoc)
     * @see com.atlassian.theplugin.crucible.api.soap.xfire.RpcAuthServiceName#login(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String login(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation login");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.atlassian.theplugin.crucible.api.soap.xfire.RpcAuthServiceName#logout(java.lang.String  arg0 )*
     */
    public void logout(java.lang.String arg0) { 
        LOG.info("Executing operation logout");
        System.out.println(arg0);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
