
package com.atlassian.theplugin.crucible.api.soap.xfire;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Thu Feb 07 14:49:09 CET 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

public final class RpcAuthServiceName_AuthPort_Client {

    private static final QName SERVICE_NAME = new QName("http://rpc.spi.crucible.atlassian.com/", "Auth");

    private RpcAuthServiceName_AuthPort_Client() {
    }

    public static void main(String args[]) throws Exception {

        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(RpcAuthServiceName.class);
        factory.setAddress("http://lech.atlassian.pl:8060/service/auth");
        RpcAuthServiceName client = (RpcAuthServiceName) factory.create();

        String reply = client.login("mwent", "d0n0tch@nge");
        System.out.println("Token:" + reply);

        System.exit(0);
    }

}
