/**
 * Copyright (C) 2008 Atlassian
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.atlassian.theplugin.idea.jira;

import com.atlassian.theplugin.idea.jira.controls.FieldDescription;
import com.atlassian.theplugin.idea.jira.controls.FieldEnvironment;
import com.atlassian.theplugin.idea.jira.controls.FieldSummary;
import com.atlassian.theplugin.jira.JiraActionFieldType;
import com.atlassian.theplugin.jira.api.JIRAActionField;
import com.atlassian.theplugin.jira.api.JIRAIssue;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * @author Jacek Jaroczynski
 */
public class PerformIssueActionForm extends DialogWrapper {
	private JPanel root;
	private JPanel contentPanel;
	private JIRAIssue issue;
	private List<JIRAActionField> fields;

	public PerformIssueActionForm(final Project project, final JIRAIssue issue, final List<JIRAActionField> fields,
			final String name) {

		super(project, true);

		this.issue = issue;
		this.fields = fields;


		$$$setupUI$$$();

		createContent(fields);

		init();
		pack();

		setTitle(name);
//		getOKAction().putValue(Action.NAME, name);
	}

	private void createContent(final List<JIRAActionField> fieldList) {

		String columns = "3dlu, right:pref, 3dlu, fill:pref:grow, 3dlu";
		String rows = "3dlu";

		rows = createLayoutRows(fieldList, rows);

		int y = 2;

		contentPanel.setLayout(new FormLayout(columns, rows));
		final CellConstraints cc = new CellConstraints();

		for (JIRAActionField field : fieldList) {

			Component component = null;

			switch (JiraActionFieldType.getFiledTypeForFieldId(field)) {
				case SUMMARY:
					component = new FieldSummary(issue);
					break;
				case DESCRIPTION:
					JTextArea description = new FieldDescription(issue);
					component = new JScrollPane(description,
							ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
					break;
				case ENVIRONMENT:
					JTextArea environment = new FieldEnvironment(issue);
					component = new JScrollPane(environment,
							ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
				case TIME_SPENT:
				case UNSUPPORTED:
				case USER:
				case VERSIONS:
				case CALENDAR:
				case COMPONENTS:
				case ISSUE_TYPE:
				case PRIORITY:
				case RESOLUTION:
				default:
					break;
			}

			if (component != null) {
				final JLabel label = new JLabel(field.getFieldId() + ":");
				contentPanel.add(label, cc.xy(2, y, CellConstraints.RIGHT, CellConstraints.TOP));

				contentPanel.add(component, cc.xy(4, y));
				y += 2;
			}
		}
	}

	private String createLayoutRows(final List<JIRAActionField> fieldList, String rows) {
		for (JIRAActionField field : fieldList) {
			switch (JiraActionFieldType.getFiledTypeForFieldId(field)) {
				case SUMMARY:
					rows += ", p, 3dlu";
					break;
				case DESCRIPTION:
				case ENVIRONMENT:
					rows += ", fill:pref:grow, 3dlu";
					break;
				case TIME_SPENT:
				case UNSUPPORTED:
				case USER:
				case VERSIONS:
				case CALENDAR:
				case COMPONENTS:
				case ISSUE_TYPE:
				case PRIORITY:
				case RESOLUTION:
				default:
					break;
			}
		}
		return rows;
	}

	protected void doOKAction() {

		// fields 

		super.doOKAction();
	}

	@Nullable
	protected JComponent createCenterPanel() {
		return root;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!

	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		root = new JPanel();
		root.setLayout(new BorderLayout(0, 0));
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setHorizontalScrollBarPolicy(31);
		root.add(scrollPane1, BorderLayout.CENTER);
		contentPanel = new JPanel();
		contentPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		scrollPane1.setViewportView(contentPanel);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return root;
	}
}
