package com.atlassian.theplugin.idea.jira;

import com.intellij.openapi.ui.DialogWrapper;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;

public class WorkLogCreate extends DialogWrapper {
	private JPanel contentPane;
	private JSpinner minutes;
	private JSpinner hours;
	private JSpinner days;
	private JSpinner weeks;
	private JTextArea comment;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridBagLayout());
		contentPane.setMinimumSize(new Dimension(700, 300));
		contentPane.setPreferredSize(new Dimension(700, 300));
		final JScrollPane scrollPane1 = new JScrollPane();
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.gridwidth = 6;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.insets = new Insets(0, 12, 12, 12);
		contentPane.add(scrollPane1, gbc);
		comment = new JTextArea();
		scrollPane1.setViewportView(comment);
		final JLabel label1 = new JLabel();
		label1.setText("Comment:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.NORTHWEST;
		gbc.insets = new Insets(0, 12, 0, 0);
		contentPane.add(label1, gbc);
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.gridwidth = 7;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.insets = new Insets(12, 12, 12, 12);
		contentPane.add(panel1, gbc);
		panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
		days = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 0;
		gbc.weightx = 0.25;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(days, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Days");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 12, 0, 12);
		panel1.add(label2, gbc);
		final JLabel label3 = new JLabel();
		label3.setText("Hours");
		gbc = new GridBagConstraints();
		gbc.gridx = 4;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 12, 0, 12);
		panel1.add(label3, gbc);
		hours = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 5;
		gbc.gridy = 0;
		gbc.weightx = 0.25;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(hours, gbc);
		final JLabel label4 = new JLabel();
		label4.setText("Minutes");
		gbc = new GridBagConstraints();
		gbc.gridx = 6;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 12, 0, 12);
		panel1.add(label4, gbc);
		minutes = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 7;
		gbc.gridy = 0;
		gbc.weightx = 0.25;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(minutes, gbc);
		final JLabel label5 = new JLabel();
		label5.setText("Weeks");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 0, 0, 12);
		panel1.add(label5, gbc);
		weeks = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 0.25;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(weeks, gbc);
		final JLabel label6 = new JLabel();
		label6.setText("Time spent:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 12, 0, 0);
		contentPane.add(label6, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

	class NonZeroChangeListener implements ChangeListener {
		public void stateChanged(ChangeEvent e) {
			boolean nonZero =
					(((Integer) weeks.getValue()).intValue()
							+ ((Integer) days.getValue()).intValue()
							+ ((Integer) hours.getValue()).intValue()
							+ ((Integer) minutes.getValue()).intValue()) > 0;
			setOKActionEnabled(nonZero);
		}
	}

	public WorkLogCreate(String issueKey) {
		super(false);
		init();
		setOKActionEnabled(false);

		setTitle("Add Worklog for " + issueKey);
		getOKAction().putValue(Action.NAME, "Add Worklog");

		weeks.setModel(new SpinnerNumberModel(0, 0, null, 1));
		days.setModel(new SpinnerNumberModel(0, 0, null, 1));
		hours.setModel(new SpinnerNumberModel(0, 0, null, 1));
		minutes.setModel(new SpinnerNumberModel(0, 0, null, 1));

		NonZeroChangeListener listener = new NonZeroChangeListener();
		weeks.addChangeListener(listener);
		days.addChangeListener(listener);
		hours.addChangeListener(listener);
		minutes.addChangeListener(listener);
	}

	public String getTimeSpentString() {
		StringBuffer b = new StringBuffer();
		b.append(weeks.getValue().toString()).append("w");
		b.append(days.getValue().toString()).append("d");
		b.append(hours.getValue().toString()).append("h");
		b.append(minutes.getValue().toString()).append("m");
		return b.toString();
	}

	public String getComment() {
		return comment.getText();
	}

	protected JComponent createCenterPanel() {
		return contentPane;
	}

}
