package com.atlassian.theplugin.idea.config.serverconfig.util;

import com.atlassian.theplugin.ServerType;
import com.atlassian.theplugin.configuration.CrucibleConfigurationBean;
import com.atlassian.theplugin.configuration.PluginConfiguration;
import com.atlassian.theplugin.configuration.PluginConfigurationBean;
import com.atlassian.theplugin.idea.config.ContentPanel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: Jacek
 * Date: 2008-03-07
 * Time: 11:30:05
 * To change this template use File | Settings | File Templates.
 */
public class CrucibleGeneralForm extends JComponent implements ContentPanel {
	private JPanel rootComponent;

	private JSpinner pollTimeSpinner;

	private PluginConfigurationBean globalPluginConfiguration;

	private SpinnerModel model;

	private CrucibleConfigurationBean crucibleConfiguration;

	private PluginConfiguration localPluginConfigurationCopy;

	public CrucibleGeneralForm(PluginConfigurationBean globalPluginConfiguration) {

		this.globalPluginConfiguration = globalPluginConfiguration;

		$$$setupUI$$$();

		model = new SpinnerNumberModel(1, 1, 1000, 1);
		pollTimeSpinner.setModel(model);

		this.setLayout(new BorderLayout());
		add(rootComponent, BorderLayout.WEST);
	}

	public boolean isEnabled() {
		return true;  //To change body of implemented methods use File | Settings | File Templates.
	}


	public boolean isModified() {
		return (Integer) model.getValue() != crucibleConfiguration.getPollTime();
	}

	public String getTitle() {
		return "Crucible";
	}

	public void getData() {

		((CrucibleConfigurationBean) getLocalPluginConfigurationCopy()
				.getProductServers(ServerType.CRUCIBLE_SERVER))
				.setPollTime((Integer) model.getValue());


		((CrucibleConfigurationBean) globalPluginConfiguration
				.getProductServers(ServerType.CRUCIBLE_SERVER))
				.setPollTime((Integer) model.getValue());
	}

	public void setData(PluginConfiguration config) {

		localPluginConfigurationCopy = config;

		crucibleConfiguration =
						(CrucibleConfigurationBean) localPluginConfigurationCopy.getProductServers(ServerType.CRUCIBLE_SERVER);

		model.setValue(crucibleConfiguration.getPollTime());


	}

	public PluginConfiguration getLocalPluginConfigurationCopy() {
		return localPluginConfigurationCopy;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootComponent = new JPanel();
		rootComponent.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow"));
		final Spacer spacer1 = new Spacer();
		CellConstraints cc = new CellConstraints();
		rootComponent.add(spacer1, cc.xy(5, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		final JLabel label1 = new JLabel();
		label1.setText("Polling time [minutes]:");
		rootComponent.add(label1, cc.xy(1, 1, CellConstraints.LEFT, CellConstraints.DEFAULT));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		rootComponent.add(panel1, cc.xy(3, 1));
		pollTimeSpinner = new JSpinner();
		panel1.add(pollTimeSpinner, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootComponent;
	}
}
