package com.atlassian.theplugin.idea.jira;

import com.atlassian.theplugin.idea.IdeaHelper;
import com.atlassian.theplugin.idea.ProgressAnimationProvider;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by IntelliJ IDEA.
 * User: pmaruszak
 * Date: Apr 8, 2008
 * Time: 10:46:37 AM
 * To change this template use File | Settings | File Templates.
 */
public class JIRAButtonPanel {
	private JPanel jiraButtonPanel;
	private JButton applyButton;
	private JButton clearButton;
	private JButton cancelButton;

	public JIRAButtonPanel() {

		$$$setupUI$$$();

		applyButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent event) {
				IdeaHelper.getCurrentJIRAToolWindowPanel().filterAndViewJiraIssues();
			}
		});


		clearButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent event) {
				final JIRAToolWindowPanel jiraPanel = IdeaHelper.getCurrentJIRAToolWindowPanel();

				if (jiraPanel != null) {

					final ProgressAnimationProvider animator = jiraPanel.getProgressAnimation();

					new Thread(new Runnable() {
						public void run() {
							animator.startProgressAnimation();
							jiraPanel.showJIRAIssueFilter();
							animator.stopProgressAnimation();
						}
					}, "JIRA show issues filter").start();

				}
					}
				});

		cancelButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent event) {
				IdeaHelper.getCurrentJIRAToolWindowPanel().hideJIRAIssuesFilter();
			}
		});

	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		jiraButtonPanel = new JPanel();
		jiraButtonPanel.setLayout(new BorderLayout(0, 0));
		jiraButtonPanel.setMinimumSize(new Dimension(350, 33));
		jiraButtonPanel.setPreferredSize(new Dimension(350, 29));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		panel1.setMinimumSize(new Dimension(-1, -1));
		jiraButtonPanel.add(panel1, BorderLayout.WEST);
		cancelButton = new JButton();
		cancelButton.setHorizontalAlignment(2);
		cancelButton.setMaximumSize(new Dimension(75, 29));
		cancelButton.setMinimumSize(new Dimension(75, 29));
		cancelButton.setText("Cancel");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel1.add(cancelButton, gbc);
		clearButton = new JButton();
		clearButton.setText("Clear");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		panel1.add(clearButton, gbc);
		applyButton = new JButton();
		applyButton.setDoubleBuffered(false);
		applyButton.setMaximumSize(new Dimension(120, 29));
		applyButton.setMinimumSize(new Dimension(120, 29));
		applyButton.setPreferredSize(new Dimension(120, 29));
		applyButton.setText("Apply");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel1.add(applyButton, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return jiraButtonPanel;
	}
}
