package com.atlassian.theplugin.idea.config.serverconfig;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: Jacek
 * Date: 2008-02-22
 * Time: 16:14:30
 * To change this template use File | Settings | File Templates.
 */
public class BambooGeneralPanel extends JPanel {
	private JRadioButton allBuildFailuresFirstRadioButton;
	private JRadioButton firstBuildFailureFirstRadioButton;
	private JRadioButton neverRadioButton;
	private JPanel rootComponent;

	public BambooGeneralPanel() {
		$$$setupUI$$$();

		add(rootComponent);
	}


	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootComponent = new JPanel();
		rootComponent.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
		allBuildFailuresFirstRadioButton = new JRadioButton();
		allBuildFailuresFirstRadioButton.setSelected(true);
		allBuildFailuresFirstRadioButton.setText("All build failures  first build success");
		allBuildFailuresFirstRadioButton.setMnemonic(' ');
		allBuildFailuresFirstRadioButton.setDisplayedMnemonicIndex(19);
		rootComponent.add(allBuildFailuresFirstRadioButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		rootComponent.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		final Spacer spacer2 = new Spacer();
		rootComponent.add(spacer2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		firstBuildFailureFirstRadioButton = new JRadioButton();
		firstBuildFailureFirstRadioButton.setText("First build failure  first build success");
		firstBuildFailureFirstRadioButton.setMnemonic(' ');
		firstBuildFailureFirstRadioButton.setDisplayedMnemonicIndex(20);
		rootComponent.add(firstBuildFailureFirstRadioButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		neverRadioButton = new JRadioButton();
		neverRadioButton.setText("Never");
		rootComponent.add(neverRadioButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("Label");
		rootComponent.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		ButtonGroup buttonGroup;
		buttonGroup = new ButtonGroup();
		buttonGroup.add(allBuildFailuresFirstRadioButton);
		buttonGroup.add(firstBuildFailureFirstRadioButton);
		buttonGroup.add(neverRadioButton);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootComponent;
	}
}
