package com.atlassian.theplugin.idea;

import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.CellConstraints;

import javax.swing.*;

/**
 * User: jgorycki
 * Date: Jan 29, 2009
 * Time: 4:56:19 PM
 */
public class AboutForm {
	private JPanel mainPanel;

	public JPanel getRootPane() {
		return mainPanel;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
		final JLabel label1 = new JLabel();
		label1.setText("About Atlassian IntelliJ Connector");
		CellConstraints cc = new CellConstraints();
		mainPanel.add(label1, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
