
package com.atlassian.theplugin.crucible.api.soap.xfire.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Feb 12 14:48:58 CET 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://rpc.spi.crucible.atlassian.com/", name = "rpcAuthServiceName")

public interface RpcAuthServiceName {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://rpc.spi.crucible.atlassian.com/", className = "com.atlassian.theplugin.crucible.api.soap.xfire.auth.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://rpc.spi.crucible.atlassian.com/", className = "com.atlassian.theplugin.crucible.api.soap.xfire.auth.LoginResponse")
    @WebMethod
    public java.lang.String login(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @RequestWrapper(localName = "logout", targetNamespace = "http://rpc.spi.crucible.atlassian.com/", className = "com.atlassian.theplugin.crucible.api.soap.xfire.auth.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://rpc.spi.crucible.atlassian.com/", className = "com.atlassian.theplugin.crucible.api.soap.xfire.auth.LogoutResponse")
    @WebMethod
    public void logout(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
