/**
 * Copyright (C) 2008 Atlassian
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * JiraSoapService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.atlassian.theplugin.jira.api.soap.axis;

public interface JiraSoapService extends java.rmi.Remote {
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteComment getComment(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteGroup createGroup(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteUser in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteUser getUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteGroup getGroup(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public java.lang.String login(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteServerInfo getServerInfo(java.lang.String in0) throws java.rmi.RemoteException;
    public boolean logout(java.lang.String in0) throws java.rmi.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue getIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteComponent[] getComponents(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteUser createUser(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue createIssue(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteNamedObject[] getAvailableActions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject[] getProjects(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue updateIssue(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteFieldValue[] in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteConfiguration getConfiguration(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject updateProject(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProject in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject getProjectByKey(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemotePriority[] getPriorities(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteResolution[] getResolutions(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssueType[] getIssueTypes(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteStatus[] getStatuses(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssueType[] getSubTaskIssueTypes(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole[] getProjectRoles(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole getProjectRole(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRoleActors getProjectRoleActors(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteProject in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteRoleActors getDefaultRoleActors(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void removeAllRoleActorsByNameAndType(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void removeAllRoleActorsByProject(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProject in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void deleteProjectRole(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1, boolean in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void updateProjectRole(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole createProjectRole(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public boolean isProjectRoleNameUnique(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void addActorsToProjectRole(java.lang.String in0, java.lang.String[] in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in2, com.atlassian.theplugin.jira.api.soap.axis.RemoteProject in3, java.lang.String in4) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void removeActorsFromProjectRole(java.lang.String in0, java.lang.String[] in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in2, com.atlassian.theplugin.jira.api.soap.axis.RemoteProject in3, java.lang.String in4) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void addDefaultActorsToProjectRole(java.lang.String in0, java.lang.String[] in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in2, java.lang.String in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void removeDefaultActorsFromProjectRole(java.lang.String in0, java.lang.String[] in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in2, java.lang.String in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteScheme[] getAssociatedNotificationSchemes(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteScheme[] getAssociatedPermissionSchemes(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProjectRole in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteField[] getCustomFields(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteFilter[] getSavedFilters(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteComment[] getComments(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void archiveVersion(java.lang.String in0, java.lang.String in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteVersion[] getVersions(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject createProject(java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3, java.lang.String in4, java.lang.String in5, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme in6, com.atlassian.theplugin.jira.api.soap.axis.RemoteScheme in7, com.atlassian.theplugin.jira.api.soap.axis.RemoteScheme in8) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void addComment(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteComment in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteField[] getFieldsForEdit(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssueType[] getIssueTypesForProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssueType[] getSubTaskIssueTypesForProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void addUserToGroup(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteGroup in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteUser in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void removeUserFromGroup(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteGroup in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteUser in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject getProjectById(java.lang.String in0, long in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void deleteProject(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void releaseVersion(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteVersion in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void deleteIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public boolean addAttachmentsToIssue(java.lang.String in0, java.lang.String in1, java.lang.String[] in2, byte[][] in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteAttachment[] getAttachmentsFromIssue(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public boolean hasPermissionToEditComment(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteComment in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteComment editComment(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteComment in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteField[] getFieldsForAction(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue progressWorkflowAction(java.lang.String in0, java.lang.String in1, java.lang.String in2, com.atlassian.theplugin.jira.api.soap.axis.RemoteFieldValue[] in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue getIssueById(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog addWorklogWithNewRemainingEstimate(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog in2, java.lang.String in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog addWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog addWorklogAndRetainRemainingEstimate(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public void deleteWorklogWithNewRemainingEstimate(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public void deleteWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public void deleteWorklogAndRetainRemainingEstimate(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public void updateWorklogWithNewRemainingEstimate(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public void updateWorklogAndAutoAdjustRemainingEstimate(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public void updateWorklogAndRetainRemainingEstimate(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteWorklog[] getWorklogs(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public boolean hasPermissionToCreateWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public boolean hasPermissionToDeleteWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public boolean hasPermissionToUpdateWorklog(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteScheme[] getNotificationSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme[] getPermissionSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme createPermissionScheme(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void deletePermissionScheme(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme addPermissionTo(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme in1, com.atlassian.theplugin.jira.api.soap.axis.RemotePermission in2, com.atlassian.theplugin.jira.api.soap.axis.RemoteEntity in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme deletePermissionFrom(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionScheme in1, com.atlassian.theplugin.jira.api.soap.axis.RemotePermission in2, com.atlassian.theplugin.jira.api.soap.axis.RemoteEntity in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemotePermission[] getAllPermissions(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public long getIssueCountForFilter(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue[] getIssuesFromTextSearch(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue[] getIssuesFromTextSearchWithProject(java.lang.String in0, java.lang.String[] in1, java.lang.String in2, int in3) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public void deleteUser(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteGroup updateGroup(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteGroup in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void deleteGroup(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public void refreshCustomFields(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject[] getProjectsNoSchemes(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteVersion addVersion(java.lang.String in0, java.lang.String in1, com.atlassian.theplugin.jira.api.soap.axis.RemoteVersion in2) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteProject createProjectFromObject(java.lang.String in0, com.atlassian.theplugin.jira.api.soap.axis.RemoteProject in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteValidationException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteScheme[] getSecuritySchemes(java.lang.String in0) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemotePermissionException, com.atlassian.theplugin.jira.api.soap.axis.RemoteAuthenticationException;
    public com.atlassian.theplugin.jira.api.soap.axis.RemoteIssue[] getIssuesFromFilter(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.theplugin.jira.api.soap.axis.RemoteException;
}
