package com.atlassian.theplugin.idea.config.serverconfig;

import com.atlassian.theplugin.ServerType;
import com.atlassian.theplugin.configuration.JiraConfigurationBean;
import com.atlassian.theplugin.configuration.PluginConfiguration;
import com.atlassian.theplugin.configuration.PluginConfigurationBean;
import com.atlassian.theplugin.idea.config.ContentPanel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: Jacek
 * Date: 2008-03-10
 * Time: 12:15:37
 * To change this template use File | Settings | File Templates.
 */
public class JiraGeneralForm extends JComponent implements ContentPanel {
	private JPanel rootComponent;
	private SpinnerModel model;
	private JSpinner pollTimeSpinner;

	private transient PluginConfigurationBean globalPluginConfiguration;
	private transient JiraConfigurationBean jiraConfiguration;
	private transient PluginConfiguration localPluginConfigurationCopy;

	public JiraGeneralForm(PluginConfigurationBean globalPluginConfiguration) {

		this.globalPluginConfiguration = globalPluginConfiguration;

		$$$setupUI$$$();
		model = new SpinnerNumberModel(1, 1, 1000, 1);
		pollTimeSpinner.setModel(model);

		this.setLayout(new BorderLayout());
		add(rootComponent, BorderLayout.WEST);
	}


	public boolean isModified() {
		return (Integer) model.getValue() != jiraConfiguration.getPollTime();
	}

	public String getTitle() {
		return "Jira";
	}

	public void getData() {

		((JiraConfigurationBean) getLocalPluginConfigurationCopy()
				.getProductServers(ServerType.JIRA_SERVER))
				.setPollTime((Integer) model.getValue());


		((JiraConfigurationBean) globalPluginConfiguration
				.getProductServers(ServerType.JIRA_SERVER))
				.setPollTime((Integer) model.getValue());
	}

	public void setData(PluginConfiguration config) {

		localPluginConfigurationCopy = config;

		jiraConfiguration =
				(JiraConfigurationBean) localPluginConfigurationCopy.getProductServers(ServerType.JIRA_SERVER);

		model.setValue(jiraConfiguration.getPollTime());


	}

	private PluginConfiguration getLocalPluginConfigurationCopy() {
		return localPluginConfigurationCopy;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rootComponent = new JPanel();
		rootComponent.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow"));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		CellConstraints cc = new CellConstraints();
		rootComponent.add(panel1, cc.xy(3, 1));
		pollTimeSpinner = new JSpinner();
		pollTimeSpinner.setEnabled(false);
		pollTimeSpinner.setToolTipText("Polling is not used for JIRA currently");
		panel1.add(pollTimeSpinner, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("Polling time [minutes]:");
		label1.setToolTipText("Polling is not used for JIRA currently");
		rootComponent.add(label1, cc.xy(1, 1));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootComponent;
	}
}
